workflows:
  android-native-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
        
    environment:
      java: 17
      groups:
        - telegram
        
    scripts:
      - name: Fetch Git Submodules (Just in case)
        script: git submodule update --init --recursive

      - name: Grant Execute Permission for Gradlew
        script: chmod +x ./gradlew
        
      - name: Generate Translations (Phrasey)
        script: |
          npm install
          npm run i18n:build
        
      - name: Build Debug APK (Clean & Optimized)
        script: ./gradlew clean assembleDebug --stacktrace --info --max-workers=2

      - name: Send APK to Telegram
        script: |
          echo "Sending APK to Telegram..."
          APK_PATH=$(find app/build/outputs/apk/debug/ -name "*arm64-v8a*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            APK_PATH=$(find app/build/outputs/apk/debug/ -name "*.apk" | head -n 1)
          fi
          
          curl -F chat_id="5368372729" \
               -F document=@"$APK_PATH" \
               -F caption="🚀 newbuild🛠" \
               http://172.245.152.11:8081/bot8060545602:AAH8aRy6T4-wmuOX2jr0ZmbCAfIJZ3FMj5w/sendDocument

    artifacts:
      - app/build/outputs/apk/debug/*.apk