package io.github.zyrouge.symphony.services.spotizer

import android.annotation.SuppressLint
import android.content.Context
import android.os.Build
import android.provider.Settings

/**
 * Handles the unified Spotizer user identity.
 *
 * - [ensureUser] is called lazily before the first request that needs a user_id
 *   (POST /v1/users/resolve with the device install id).
 * - [linkWithCode] exchanges a one-time code generated by the Telegram bot so
 *   app + bot share history and settings (POST /v1/users/link).
 */
class SpotizerUserManager(
    private val context: Context,
    private val client: SpotizerClient,
    private val settings: SpotizerSettings,
) {
    @SuppressLint("HardwareIds")
    private fun platformUserId(): String {
        val androidId = Settings.Secure.getString(
            context.contentResolver,
            Settings.Secure.ANDROID_ID,
        ) ?: "unknown"
        return "android_$androidId"
    }

    private fun displayName(): String = "${Build.MANUFACTURER} ${Build.MODEL}".trim().take(255)

    /** Returns the unified user_id, resolving it on first use. */
    suspend fun ensureUser(): Long {
        settings.userId?.let { return it }
        val response = client.resolveUser(
            ResolveRequest(
                platformUserId = platformUserId(),
                displayName = displayName(),
            )
        )
        settings.setUserId(response.userId)
        return response.userId
    }

    /** Link this device to an existing bot account using a one-time code. */
    suspend fun linkWithCode(code: String): ResolveResponse {
        val response = client.linkWithCode(
            LinkRequest(
                code = code.trim(),
                platformUserId = platformUserId(),
                displayName = displayName(),
            )
        )
        settings.setUserId(response.userId)
        return response
    }

    /** Push the local default download quality to the server-side settings. */
    suspend fun syncQualityToServer() {
        val userId = ensureUser()
        client.updateServerSettings(userId, SettingsUpdate(quality = settings.downloadQuality.value))
    }
}
